baseurl: '/carpediem'
permalink: pretty
title: 'Institut Carpe Diem'

logo:
  mobile: "images/logo/logo-mobile.webp"
  mobile_height: "33px"
  mobile_width: "40px"
  desktop: "images/logo/logo-1.webp"
  desktop_height: "195px"
  desktop_width: "200px"
  footer: "images/logo/logo-footer.webp"
  footer_height: "50px"
  footer_width: "100px"

collections:
  services:
    output: true
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  indentWidth: 4
  style: compressed # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-imagemagick

imagemagick:
  enabled: true
  widths:
    - 0
  input_directories:
    - images
    - images/features
    - images/illustrations
    - images/post
    - images/logo
    - images/team


  input_formats:
    - ".png"
    - ".jpeg"
    - ".jpg"
    - ".tiff"
  output_formats:
#    jpg: "-quality 93% -define jpeg:dct-method=float -strip -interlace Plane"
    webp: "-quality 80%"


exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
